CREATE TABLE mc_script_execution_task (
    id VARCHAR(64) NOT NULL PRIMARY KEY,
    script_id VARCHAR(64) NOT NULL,
    script_name VARCHAR(255) NOT NULL,
    service_name VARCHAR(255) NOT NULL,
    environment VARCHAR(64) NOT NULL,
    selection_mode VARCHAR(32) NOT NULL,
    requested_instance_id VARCHAR(255),
    executor_id VARCHAR(64) NOT NULL,
    executor_name VARCHAR(255) NOT NULL,
    script_content MEDIUMTEXT NOT NULL,
    final_script_content MEDIUMTEXT NOT NULL,
    parameters MEDIUMTEXT,
    status VARCHAR(32) NOT NULL,
    targets_json MEDIUMTEXT NOT NULL,
    timeout_seconds INT NOT NULL,
    cancel_requested TINYINT(1) NOT NULL DEFAULT 0,
    error_message TEXT,
    create_time DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    start_time DATETIME(6),
    end_time DATETIME(6),
    duration INT,
    CONSTRAINT fk_execution_task_script FOREIGN KEY (script_id) REFERENCES mc_script (id),
    INDEX idx_execution_task_script (script_id, create_time DESC),
    INDEX idx_execution_task_executor (executor_id, create_time DESC),
    INDEX idx_execution_task_status (status, create_time)
);
